### ISSUE TITLE
android 10 点击拍照 没有效果。没有获取到摄像帧数

### ISSUE THREAD

**Issue by zhoujianli1016** [Giftedcat/CameraTakeManager#1]
红米K30

**Comment by TonyChenn** [comment]
> 红米K30

我也是Android 10, 可以用的。

**Comment by Giftedcat** [comment]
云测平台暂时没有红米K30的机型，麻烦兄弟如果有error的日志上一下

**Comment by zhoujianli1016** [comment]
对不起，我的问题，是因为android10的分区存储问题，加上requestLegacyExternalStorage="true"就行
